#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EvotingDB")]
public partial class Lsc_EVotingDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblJozeiatRai(tblJozeiatRai instance);
  partial void UpdatetblJozeiatRai(tblJozeiatRai instance);
  partial void DeletetblJozeiatRai(tblJozeiatRai instance);
  partial void InserttblRaigiriTitle(tblRaigiriTitle instance);
  partial void UpdatetblRaigiriTitle(tblRaigiriTitle instance);
  partial void DeletetblRaigiriTitle(tblRaigiriTitle instance);
  partial void InserttblUser(tblUser instance);
  partial void UpdatetblUser(tblUser instance);
  partial void DeletetblUser(tblUser instance);
  partial void InserttblUserType(tblUserType instance);
  partial void UpdatetblUserType(tblUserType instance);
  partial void DeletetblUserType(tblUserType instance);
  partial void InserttblRaidahandegan(tblRaidahandegan instance);
  partial void UpdatetblRaidahandegan(tblRaidahandegan instance);
  partial void DeletetblRaidahandegan(tblRaidahandegan instance);
  partial void InserttblMessage(tblMessage instance);
  partial void UpdatetblMessage(tblMessage instance);
  partial void DeletetblMessage(tblMessage instance);
  partial void InserttblLink(tblLink instance);
  partial void UpdatetblLink(tblLink instance);
  partial void DeletetblLink(tblLink instance);
  #endregion
	
	public Lsc_EVotingDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EvotingDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public Lsc_EVotingDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Lsc_EVotingDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Lsc_EVotingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Lsc_EVotingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblJozeiatRai> tblJozeiatRais
	{
		get
		{
			return this.GetTable<tblJozeiatRai>();
		}
	}
	
	public System.Data.Linq.Table<tblRaigiriTitle> tblRaigiriTitles
	{
		get
		{
			return this.GetTable<tblRaigiriTitle>();
		}
	}
	
	public System.Data.Linq.Table<tblUser> tblUsers
	{
		get
		{
			return this.GetTable<tblUser>();
		}
	}
	
	public System.Data.Linq.Table<tblUserType> tblUserTypes
	{
		get
		{
			return this.GetTable<tblUserType>();
		}
	}
	
	public System.Data.Linq.Table<tblRaidahandegan> tblRaidahandegans
	{
		get
		{
			return this.GetTable<tblRaidahandegan>();
		}
	}
	
	public System.Data.Linq.Table<xtblJozeiatRai> xtblJozeiatRais
	{
		get
		{
			return this.GetTable<xtblJozeiatRai>();
		}
	}
	
	public System.Data.Linq.Table<tblMessage> tblMessages
	{
		get
		{
			return this.GetTable<tblMessage>();
		}
	}
	
	public System.Data.Linq.Table<tblLink> tblLinks
	{
		get
		{
			return this.GetTable<tblLink>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblJozeiatRai")]
public partial class tblJozeiatRai : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _JozeiatRaiId;
	
	private System.Nullable<int> _RaigiriTitleId;
	
	private System.Nullable<decimal> _RaiQuantity;
	
	private string _KandidName;
	
	private EntitySet<tblRaidahandegan> _tblRaidahandegans;
	
	private EntityRef<tblRaigiriTitle> _tblRaigiriTitle;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJozeiatRaiIdChanging(decimal value);
    partial void OnJozeiatRaiIdChanged();
    partial void OnRaigiriTitleIdChanging(System.Nullable<int> value);
    partial void OnRaigiriTitleIdChanged();
    partial void OnRaiQuantityChanging(System.Nullable<decimal> value);
    partial void OnRaiQuantityChanged();
    partial void OnKandidNameChanging(string value);
    partial void OnKandidNameChanged();
    #endregion
	
	public tblJozeiatRai()
	{
		this._tblRaidahandegans = new EntitySet<tblRaidahandegan>(new Action<tblRaidahandegan>(this.attach_tblRaidahandegans), new Action<tblRaidahandegan>(this.detach_tblRaidahandegans));
		this._tblRaigiriTitle = default(EntityRef<tblRaigiriTitle>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JozeiatRaiId", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal JozeiatRaiId
	{
		get
		{
			return this._JozeiatRaiId;
		}
		set
		{
			if ((this._JozeiatRaiId != value))
			{
				this.OnJozeiatRaiIdChanging(value);
				this.SendPropertyChanging();
				this._JozeiatRaiId = value;
				this.SendPropertyChanged("JozeiatRaiId");
				this.OnJozeiatRaiIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaigiriTitleId", DbType="Int")]
	public System.Nullable<int> RaigiriTitleId
	{
		get
		{
			return this._RaigiriTitleId;
		}
		set
		{
			if ((this._RaigiriTitleId != value))
			{
				if (this._tblRaigiriTitle.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnRaigiriTitleIdChanging(value);
				this.SendPropertyChanging();
				this._RaigiriTitleId = value;
				this.SendPropertyChanged("RaigiriTitleId");
				this.OnRaigiriTitleIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaiQuantity", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> RaiQuantity
	{
		get
		{
			return this._RaiQuantity;
		}
		set
		{
			if ((this._RaiQuantity != value))
			{
				this.OnRaiQuantityChanging(value);
				this.SendPropertyChanging();
				this._RaiQuantity = value;
				this.SendPropertyChanged("RaiQuantity");
				this.OnRaiQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KandidName", DbType="NVarChar(50)")]
	public string KandidName
	{
		get
		{
			return this._KandidName;
		}
		set
		{
			if ((this._KandidName != value))
			{
				this.OnKandidNameChanging(value);
				this.SendPropertyChanging();
				this._KandidName = value;
				this.SendPropertyChanged("KandidName");
				this.OnKandidNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblJozeiatRai_tblRaidahandegan", Storage="_tblRaidahandegans", ThisKey="JozeiatRaiId", OtherKey="JozeiatRaiId")]
	public EntitySet<tblRaidahandegan> tblRaidahandegans
	{
		get
		{
			return this._tblRaidahandegans;
		}
		set
		{
			this._tblRaidahandegans.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblRaigiriTitle_tblJozeiatRai", Storage="_tblRaigiriTitle", ThisKey="RaigiriTitleId", OtherKey="RaigiriTitleId", IsForeignKey=true, DeleteRule="CASCADE")]
	public tblRaigiriTitle tblRaigiriTitle
	{
		get
		{
			return this._tblRaigiriTitle.Entity;
		}
		set
		{
			tblRaigiriTitle previousValue = this._tblRaigiriTitle.Entity;
			if (((previousValue != value) 
						|| (this._tblRaigiriTitle.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblRaigiriTitle.Entity = null;
					previousValue.tblJozeiatRais.Remove(this);
				}
				this._tblRaigiriTitle.Entity = value;
				if ((value != null))
				{
					value.tblJozeiatRais.Add(this);
					this._RaigiriTitleId = value.RaigiriTitleId;
				}
				else
				{
					this._RaigiriTitleId = default(Nullable<int>);
				}
				this.SendPropertyChanged("tblRaigiriTitle");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblRaidahandegans(tblRaidahandegan entity)
	{
		this.SendPropertyChanging();
		entity.tblJozeiatRai = this;
	}
	
	private void detach_tblRaidahandegans(tblRaidahandegan entity)
	{
		this.SendPropertyChanging();
		entity.tblJozeiatRai = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRaigiriTitle")]
public partial class tblRaigiriTitle : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _RaigiriTitleId;
	
	private string _RaigiriName;
	
	private System.Nullable<bool> _CloseBit;
	
	private string _DateCreation;
	
	private string _DateFinish;
	
	private EntitySet<tblJozeiatRai> _tblJozeiatRais;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRaigiriTitleIdChanging(int value);
    partial void OnRaigiriTitleIdChanged();
    partial void OnRaigiriNameChanging(string value);
    partial void OnRaigiriNameChanged();
    partial void OnCloseBitChanging(System.Nullable<bool> value);
    partial void OnCloseBitChanged();
    partial void OnDateCreationChanging(string value);
    partial void OnDateCreationChanged();
    partial void OnDateFinishChanging(string value);
    partial void OnDateFinishChanged();
    #endregion
	
	public tblRaigiriTitle()
	{
		this._tblJozeiatRais = new EntitySet<tblJozeiatRai>(new Action<tblJozeiatRai>(this.attach_tblJozeiatRais), new Action<tblJozeiatRai>(this.detach_tblJozeiatRais));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaigiriTitleId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int RaigiriTitleId
	{
		get
		{
			return this._RaigiriTitleId;
		}
		set
		{
			if ((this._RaigiriTitleId != value))
			{
				this.OnRaigiriTitleIdChanging(value);
				this.SendPropertyChanging();
				this._RaigiriTitleId = value;
				this.SendPropertyChanged("RaigiriTitleId");
				this.OnRaigiriTitleIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaigiriName", DbType="NVarChar(200)")]
	public string RaigiriName
	{
		get
		{
			return this._RaigiriName;
		}
		set
		{
			if ((this._RaigiriName != value))
			{
				this.OnRaigiriNameChanging(value);
				this.SendPropertyChanging();
				this._RaigiriName = value;
				this.SendPropertyChanged("RaigiriName");
				this.OnRaigiriNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseBit", DbType="Bit")]
	public System.Nullable<bool> CloseBit
	{
		get
		{
			return this._CloseBit;
		}
		set
		{
			if ((this._CloseBit != value))
			{
				this.OnCloseBitChanging(value);
				this.SendPropertyChanging();
				this._CloseBit = value;
				this.SendPropertyChanged("CloseBit");
				this.OnCloseBitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreation", DbType="NVarChar(50)")]
	public string DateCreation
	{
		get
		{
			return this._DateCreation;
		}
		set
		{
			if ((this._DateCreation != value))
			{
				this.OnDateCreationChanging(value);
				this.SendPropertyChanging();
				this._DateCreation = value;
				this.SendPropertyChanged("DateCreation");
				this.OnDateCreationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFinish", DbType="NVarChar(50)")]
	public string DateFinish
	{
		get
		{
			return this._DateFinish;
		}
		set
		{
			if ((this._DateFinish != value))
			{
				this.OnDateFinishChanging(value);
				this.SendPropertyChanging();
				this._DateFinish = value;
				this.SendPropertyChanged("DateFinish");
				this.OnDateFinishChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblRaigiriTitle_tblJozeiatRai", Storage="_tblJozeiatRais", ThisKey="RaigiriTitleId", OtherKey="RaigiriTitleId")]
	public EntitySet<tblJozeiatRai> tblJozeiatRais
	{
		get
		{
			return this._tblJozeiatRais;
		}
		set
		{
			this._tblJozeiatRais.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblJozeiatRais(tblJozeiatRai entity)
	{
		this.SendPropertyChanging();
		entity.tblRaigiriTitle = this;
	}
	
	private void detach_tblJozeiatRais(tblJozeiatRai entity)
	{
		this.SendPropertyChanging();
		entity.tblRaigiriTitle = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsers")]
public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _UserID;
	
	private string _UsersName;
	
	private string _UsersPwa;
	
	private string _NameOfUser;
	
	private string _SnameOfUser;
	
	private int _UserTypeID;
	
	private string _UserEmail;
	
	private string _UserMobilePhone;
	
	private EntitySet<tblRaidahandegan> _tblRaidahandegans;
	
	private EntityRef<tblUserType> _tblUserType;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(decimal value);
    partial void OnUserIDChanged();
    partial void OnUsersNameChanging(string value);
    partial void OnUsersNameChanged();
    partial void OnUsersPwaChanging(string value);
    partial void OnUsersPwaChanged();
    partial void OnNameOfUserChanging(string value);
    partial void OnNameOfUserChanged();
    partial void OnSnameOfUserChanging(string value);
    partial void OnSnameOfUserChanged();
    partial void OnUserTypeIDChanging(int value);
    partial void OnUserTypeIDChanged();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnUserMobilePhoneChanging(string value);
    partial void OnUserMobilePhoneChanged();
    #endregion
	
	public tblUser()
	{
		this._tblRaidahandegans = new EntitySet<tblRaidahandegan>(new Action<tblRaidahandegan>(this.attach_tblRaidahandegans), new Action<tblRaidahandegan>(this.detach_tblRaidahandegans));
		this._tblUserType = default(EntityRef<tblUserType>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
	public decimal UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersName", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string UsersName
	{
		get
		{
			return this._UsersName;
		}
		set
		{
			if ((this._UsersName != value))
			{
				this.OnUsersNameChanging(value);
				this.SendPropertyChanging();
				this._UsersName = value;
				this.SendPropertyChanged("UsersName");
				this.OnUsersNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersPwa", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string UsersPwa
	{
		get
		{
			return this._UsersPwa;
		}
		set
		{
			if ((this._UsersPwa != value))
			{
				this.OnUsersPwaChanging(value);
				this.SendPropertyChanging();
				this._UsersPwa = value;
				this.SendPropertyChanged("UsersPwa");
				this.OnUsersPwaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOfUser", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string NameOfUser
	{
		get
		{
			return this._NameOfUser;
		}
		set
		{
			if ((this._NameOfUser != value))
			{
				this.OnNameOfUserChanging(value);
				this.SendPropertyChanging();
				this._NameOfUser = value;
				this.SendPropertyChanged("NameOfUser");
				this.OnNameOfUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SnameOfUser", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string SnameOfUser
	{
		get
		{
			return this._SnameOfUser;
		}
		set
		{
			if ((this._SnameOfUser != value))
			{
				this.OnSnameOfUserChanging(value);
				this.SendPropertyChanging();
				this._SnameOfUser = value;
				this.SendPropertyChanged("SnameOfUser");
				this.OnSnameOfUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTypeID", DbType="Int NOT NULL")]
	public int UserTypeID
	{
		get
		{
			return this._UserTypeID;
		}
		set
		{
			if ((this._UserTypeID != value))
			{
				if (this._tblUserType.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUserTypeIDChanging(value);
				this.SendPropertyChanging();
				this._UserTypeID = value;
				this.SendPropertyChanged("UserTypeID");
				this.OnUserTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string UserEmail
	{
		get
		{
			return this._UserEmail;
		}
		set
		{
			if ((this._UserEmail != value))
			{
				this.OnUserEmailChanging(value);
				this.SendPropertyChanging();
				this._UserEmail = value;
				this.SendPropertyChanged("UserEmail");
				this.OnUserEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserMobilePhone", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string UserMobilePhone
	{
		get
		{
			return this._UserMobilePhone;
		}
		set
		{
			if ((this._UserMobilePhone != value))
			{
				this.OnUserMobilePhoneChanging(value);
				this.SendPropertyChanging();
				this._UserMobilePhone = value;
				this.SendPropertyChanged("UserMobilePhone");
				this.OnUserMobilePhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblRaidahandegan", Storage="_tblRaidahandegans", ThisKey="UsersName", OtherKey="UsersNmae")]
	public EntitySet<tblRaidahandegan> tblRaidahandegans
	{
		get
		{
			return this._tblRaidahandegans;
		}
		set
		{
			this._tblRaidahandegans.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUserType_tblUser", Storage="_tblUserType", ThisKey="UserTypeID", OtherKey="UserTypeID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public tblUserType tblUserType
	{
		get
		{
			return this._tblUserType.Entity;
		}
		set
		{
			tblUserType previousValue = this._tblUserType.Entity;
			if (((previousValue != value) 
						|| (this._tblUserType.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblUserType.Entity = null;
					previousValue.tblUsers.Remove(this);
				}
				this._tblUserType.Entity = value;
				if ((value != null))
				{
					value.tblUsers.Add(this);
					this._UserTypeID = value.UserTypeID;
				}
				else
				{
					this._UserTypeID = default(int);
				}
				this.SendPropertyChanged("tblUserType");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblRaidahandegans(tblRaidahandegan entity)
	{
		this.SendPropertyChanging();
		entity.tblUser = this;
	}
	
	private void detach_tblRaidahandegans(tblRaidahandegan entity)
	{
		this.SendPropertyChanging();
		entity.tblUser = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUserTypes")]
public partial class tblUserType : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _UserTypeID;
	
	private string _UserTypeDescription;
	
	private EntitySet<tblUser> _tblUsers;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserTypeIDChanging(int value);
    partial void OnUserTypeIDChanged();
    partial void OnUserTypeDescriptionChanging(string value);
    partial void OnUserTypeDescriptionChanged();
    #endregion
	
	public tblUserType()
	{
		this._tblUsers = new EntitySet<tblUser>(new Action<tblUser>(this.attach_tblUsers), new Action<tblUser>(this.detach_tblUsers));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int UserTypeID
	{
		get
		{
			return this._UserTypeID;
		}
		set
		{
			if ((this._UserTypeID != value))
			{
				this.OnUserTypeIDChanging(value);
				this.SendPropertyChanging();
				this._UserTypeID = value;
				this.SendPropertyChanged("UserTypeID");
				this.OnUserTypeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserTypeDescription", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string UserTypeDescription
	{
		get
		{
			return this._UserTypeDescription;
		}
		set
		{
			if ((this._UserTypeDescription != value))
			{
				this.OnUserTypeDescriptionChanging(value);
				this.SendPropertyChanging();
				this._UserTypeDescription = value;
				this.SendPropertyChanged("UserTypeDescription");
				this.OnUserTypeDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUserType_tblUser", Storage="_tblUsers", ThisKey="UserTypeID", OtherKey="UserTypeID")]
	public EntitySet<tblUser> tblUsers
	{
		get
		{
			return this._tblUsers;
		}
		set
		{
			this._tblUsers.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tblUsers(tblUser entity)
	{
		this.SendPropertyChanging();
		entity.tblUserType = this;
	}
	
	private void detach_tblUsers(tblUser entity)
	{
		this.SendPropertyChanging();
		entity.tblUserType = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRaidahandegan")]
public partial class tblRaidahandegan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _RaiDahandaId;
	
	private string _UsersNmae;
	
	private System.Nullable<decimal> _JozeiatRaiId;
	
	private string _DateRai;
	
	private EntityRef<tblJozeiatRai> _tblJozeiatRai;
	
	private EntityRef<tblUser> _tblUser;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRaiDahandaIdChanging(decimal value);
    partial void OnRaiDahandaIdChanged();
    partial void OnUsersNmaeChanging(string value);
    partial void OnUsersNmaeChanged();
    partial void OnJozeiatRaiIdChanging(System.Nullable<decimal> value);
    partial void OnJozeiatRaiIdChanged();
    partial void OnDateRaiChanging(string value);
    partial void OnDateRaiChanged();
    #endregion
	
	public tblRaidahandegan()
	{
		this._tblJozeiatRai = default(EntityRef<tblJozeiatRai>);
		this._tblUser = default(EntityRef<tblUser>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaiDahandaId", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal RaiDahandaId
	{
		get
		{
			return this._RaiDahandaId;
		}
		set
		{
			if ((this._RaiDahandaId != value))
			{
				this.OnRaiDahandaIdChanging(value);
				this.SendPropertyChanging();
				this._RaiDahandaId = value;
				this.SendPropertyChanged("RaiDahandaId");
				this.OnRaiDahandaIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersNmae", DbType="NVarChar(150)")]
	public string UsersNmae
	{
		get
		{
			return this._UsersNmae;
		}
		set
		{
			if ((this._UsersNmae != value))
			{
				if (this._tblUser.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUsersNmaeChanging(value);
				this.SendPropertyChanging();
				this._UsersNmae = value;
				this.SendPropertyChanged("UsersNmae");
				this.OnUsersNmaeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JozeiatRaiId", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> JozeiatRaiId
	{
		get
		{
			return this._JozeiatRaiId;
		}
		set
		{
			if ((this._JozeiatRaiId != value))
			{
				if (this._tblJozeiatRai.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnJozeiatRaiIdChanging(value);
				this.SendPropertyChanging();
				this._JozeiatRaiId = value;
				this.SendPropertyChanged("JozeiatRaiId");
				this.OnJozeiatRaiIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRai", DbType="NVarChar(10)")]
	public string DateRai
	{
		get
		{
			return this._DateRai;
		}
		set
		{
			if ((this._DateRai != value))
			{
				this.OnDateRaiChanging(value);
				this.SendPropertyChanging();
				this._DateRai = value;
				this.SendPropertyChanged("DateRai");
				this.OnDateRaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblJozeiatRai_tblRaidahandegan", Storage="_tblJozeiatRai", ThisKey="JozeiatRaiId", OtherKey="JozeiatRaiId", IsForeignKey=true, DeleteRule="CASCADE")]
	public tblJozeiatRai tblJozeiatRai
	{
		get
		{
			return this._tblJozeiatRai.Entity;
		}
		set
		{
			tblJozeiatRai previousValue = this._tblJozeiatRai.Entity;
			if (((previousValue != value) 
						|| (this._tblJozeiatRai.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblJozeiatRai.Entity = null;
					previousValue.tblRaidahandegans.Remove(this);
				}
				this._tblJozeiatRai.Entity = value;
				if ((value != null))
				{
					value.tblRaidahandegans.Add(this);
					this._JozeiatRaiId = value.JozeiatRaiId;
				}
				else
				{
					this._JozeiatRaiId = default(Nullable<decimal>);
				}
				this.SendPropertyChanged("tblJozeiatRai");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblRaidahandegan", Storage="_tblUser", ThisKey="UsersNmae", OtherKey="UsersName", IsForeignKey=true, DeleteRule="CASCADE")]
	public tblUser tblUser
	{
		get
		{
			return this._tblUser.Entity;
		}
		set
		{
			tblUser previousValue = this._tblUser.Entity;
			if (((previousValue != value) 
						|| (this._tblUser.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tblUser.Entity = null;
					previousValue.tblRaidahandegans.Remove(this);
				}
				this._tblUser.Entity = value;
				if ((value != null))
				{
					value.tblRaidahandegans.Add(this);
					this._UsersNmae = value.UsersName;
				}
				else
				{
					this._UsersNmae = default(string);
				}
				this.SendPropertyChanged("tblUser");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xtblJozeiatRai")]
public partial class xtblJozeiatRai
{
	
	private decimal _JozeiatRaiId;
	
	private string _RaigiriName;
	
	private System.Nullable<decimal> _RaiQuantity;
	
	private string _KandidName;
	
	private int _RaigiriTitleId;
	
	public xtblJozeiatRai()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JozeiatRaiId", DbType="Decimal(18,0) NOT NULL")]
	public decimal JozeiatRaiId
	{
		get
		{
			return this._JozeiatRaiId;
		}
		set
		{
			if ((this._JozeiatRaiId != value))
			{
				this._JozeiatRaiId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaigiriName", DbType="NVarChar(200)")]
	public string RaigiriName
	{
		get
		{
			return this._RaigiriName;
		}
		set
		{
			if ((this._RaigiriName != value))
			{
				this._RaigiriName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaiQuantity", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> RaiQuantity
	{
		get
		{
			return this._RaiQuantity;
		}
		set
		{
			if ((this._RaiQuantity != value))
			{
				this._RaiQuantity = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KandidName", DbType="NVarChar(50)")]
	public string KandidName
	{
		get
		{
			return this._KandidName;
		}
		set
		{
			if ((this._KandidName != value))
			{
				this._KandidName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaigiriTitleId", DbType="Int NOT NULL")]
	public int RaigiriTitleId
	{
		get
		{
			return this._RaigiriTitleId;
		}
		set
		{
			if ((this._RaigiriTitleId != value))
			{
				this._RaigiriTitleId = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMessage")]
public partial class tblMessage : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _MessageId;
	
	private string _Name;
	
	private string _Email;
	
	private string _message;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMessageIdChanging(decimal value);
    partial void OnMessageIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    #endregion
	
	public tblMessage()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageId", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal MessageId
	{
		get
		{
			return this._MessageId;
		}
		set
		{
			if ((this._MessageId != value))
			{
				this.OnMessageIdChanging(value);
				this.SendPropertyChanging();
				this._MessageId = value;
				this.SendPropertyChanged("MessageId");
				this.OnMessageIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(400)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(400)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="NVarChar(500)")]
	public string message
	{
		get
		{
			return this._message;
		}
		set
		{
			if ((this._message != value))
			{
				this.OnmessageChanging(value);
				this.SendPropertyChanging();
				this._message = value;
				this.SendPropertyChanged("message");
				this.OnmessageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLinks")]
public partial class tblLink : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _LinlId;
	
	private string _LinkTitle;
	
	private string _LinkPath;
	
	private System.Nullable<int> _LinkSortNumber;
	
	private System.Nullable<bool> _AlllowAdmin;
	
	private System.Nullable<bool> _AllowRegisterUsers;
	
	private System.Nullable<bool> _AllowUsualy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLinlIdChanging(int value);
    partial void OnLinlIdChanged();
    partial void OnLinkTitleChanging(string value);
    partial void OnLinkTitleChanged();
    partial void OnLinkPathChanging(string value);
    partial void OnLinkPathChanged();
    partial void OnLinkSortNumberChanging(System.Nullable<int> value);
    partial void OnLinkSortNumberChanged();
    partial void OnAlllowAdminChanging(System.Nullable<bool> value);
    partial void OnAlllowAdminChanged();
    partial void OnAllowRegisterUsersChanging(System.Nullable<bool> value);
    partial void OnAllowRegisterUsersChanged();
    partial void OnAllowUsualyChanging(System.Nullable<bool> value);
    partial void OnAllowUsualyChanged();
    #endregion
	
	public tblLink()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinlId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int LinlId
	{
		get
		{
			return this._LinlId;
		}
		set
		{
			if ((this._LinlId != value))
			{
				this.OnLinlIdChanging(value);
				this.SendPropertyChanging();
				this._LinlId = value;
				this.SendPropertyChanged("LinlId");
				this.OnLinlIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkTitle", DbType="NVarChar(100)")]
	public string LinkTitle
	{
		get
		{
			return this._LinkTitle;
		}
		set
		{
			if ((this._LinkTitle != value))
			{
				this.OnLinkTitleChanging(value);
				this.SendPropertyChanging();
				this._LinkTitle = value;
				this.SendPropertyChanged("LinkTitle");
				this.OnLinkTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkPath", DbType="NVarChar(150)")]
	public string LinkPath
	{
		get
		{
			return this._LinkPath;
		}
		set
		{
			if ((this._LinkPath != value))
			{
				this.OnLinkPathChanging(value);
				this.SendPropertyChanging();
				this._LinkPath = value;
				this.SendPropertyChanged("LinkPath");
				this.OnLinkPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkSortNumber", DbType="Int")]
	public System.Nullable<int> LinkSortNumber
	{
		get
		{
			return this._LinkSortNumber;
		}
		set
		{
			if ((this._LinkSortNumber != value))
			{
				this.OnLinkSortNumberChanging(value);
				this.SendPropertyChanging();
				this._LinkSortNumber = value;
				this.SendPropertyChanged("LinkSortNumber");
				this.OnLinkSortNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlllowAdmin", DbType="Bit")]
	public System.Nullable<bool> AlllowAdmin
	{
		get
		{
			return this._AlllowAdmin;
		}
		set
		{
			if ((this._AlllowAdmin != value))
			{
				this.OnAlllowAdminChanging(value);
				this.SendPropertyChanging();
				this._AlllowAdmin = value;
				this.SendPropertyChanged("AlllowAdmin");
				this.OnAlllowAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowRegisterUsers", DbType="Bit")]
	public System.Nullable<bool> AllowRegisterUsers
	{
		get
		{
			return this._AllowRegisterUsers;
		}
		set
		{
			if ((this._AllowRegisterUsers != value))
			{
				this.OnAllowRegisterUsersChanging(value);
				this.SendPropertyChanging();
				this._AllowRegisterUsers = value;
				this.SendPropertyChanged("AllowRegisterUsers");
				this.OnAllowRegisterUsersChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowUsualy", DbType="Bit")]
	public System.Nullable<bool> AllowUsualy
	{
		get
		{
			return this._AllowUsualy;
		}
		set
		{
			if ((this._AllowUsualy != value))
			{
				this.OnAllowUsualyChanging(value);
				this.SendPropertyChanging();
				this._AllowUsualy = value;
				this.SendPropertyChanged("AllowUsualy");
				this.OnAllowUsualyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
